# Pandas DataFrame Detective

In [25]:
import numpy as np
import pandas as pd

dict = pd.DataFrame ({'Name': ['Alice','Bob','Charlie','Diana','Eve','Frank'],
                     'Age': [25,30,np.nan,35,28,np.nan],
                     'Score': [85,92,78,np.nan,88,95],
                     'Grade': ['A','A','B','C','B','A']}) 

df = dict
df

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B
3    Diana  35.0    NaN     C
4      Eve  28.0   88.0     B
5    Frank   NaN   95.0     A

In [26]:
df.head(3)

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie   NaN   78.0     B

In [27]:
df.shape

(6, 4)

In [28]:
df.columns

Index(['Name', 'Age', 'Score', 'Grade'], dtype='str')

In [29]:
df.dtypes

Name         str
Age      float64
Score    float64
Grade        str
dtype: object

In [30]:
df.isnull().sum()

Name     0
Age      2
Score    1
Grade    0
dtype: int64

In [38]:
m = df['Age'].mean()
m

np.float64(29.5)

In [39]:
df['Age'] = df['Age'].fillna(m)
df['Age']

0    25.0
1    30.0
2    29.5
3    35.0
4    28.0
5    29.5
Name: Age, dtype: float64

In [42]:
df.dropna()

      Name   Age  Score Grade
0    Alice  25.0   85.0     A
1      Bob  30.0   92.0     A
2  Charlie  29.5   78.0     B
4      Eve  28.0   88.0     B
5    Frank  29.5   95.0     A

In [45]:
df[['Name' , 'Score']]

      Name  Score
0    Alice   85.0
1      Bob   92.0
2  Charlie   78.0
3    Diana    NaN
4      Eve   88.0
5    Frank   95.0

In [46]:
df[df['Score'] > 85]

    Name   Age  Score Grade
1    Bob  30.0   92.0     A
4    Eve  28.0   88.0     B
5  Frank  29.5   95.0     A

In [47]:
df.set_index('Name')

          Age  Score Grade
Name
Alice    25.0   85.0     A
Bob      30.0   92.0     A
Charlie  29.5   78.0     B
Diana    35.0    NaN     C
Eve      28.0   88.0     B
Frank    29.5   95.0     A

In [48]:
df['Grade'].unique()

<StringArray>
['A', 'B', 'C']
Length: 3, dtype: str

In [49]:
df['Grade'].count()

np.int64(6)

In [50]:
df.sort_values('Score' , ascending=False)

      Name   Age  Score Grade
5    Frank  29.5   95.0     A
1      Bob  30.0   92.0     A
4      Eve  28.0   88.0     B
0    Alice  25.0   85.0     A
2  Charlie  29.5   78.0     B
3    Diana  35.0    NaN     C

In [ ]:
arr[2:4,3:5]